mv wi-thermometer.svg flowers/
mv wi-night-cloudy-gusts.svg flowers/
mv wi-night-cloudy-high.svg flowers/
mv wi-night-alt-cloudy-windy.svg flowers/
mv wi-night-alt-cloudy-gusts.svg flowers/
mv wi-night-alt-cloudy-high.svg flowers/
mv wi-night-alt-cloudy.svg flowers/
mv wi-night-alt-sprinkle.svg flowers/
mv wi-night-alt-thunderstorm.svg flowers/
mv wi-night-alt-storm-showers.svg flowers/
mv wi-night-alt-snow-wind.svg flowers/
mv wi-night-alt-snow-thunderstorm.svg flowers/
mv wi-night-alt-snow.svg flowers/
mv wi-night-alt-sleet.svg flowers/
mv wi-night-alt-showers.svg flowers/
mv wi-night-alt-rain-mix.svg flowers/
mv wi-night-alt-rain.svg flowers/
mv wi-night-alt-hail.svg flowers/
mv wi-night-rain.svg flowers/
mv wi-day-sprinkle.svg flowers/
mv wi-day-snow-thunderstorm.svg flowers/
mv wi-day-storm-showers.svg flowers/
mv wi-night-alt-lightning.svg flowers/
mv wi-night-lightning.svg flowers/
mv wi-night-hail.svg flowers/
mv wi-day-rain-wind.svg flowers/
mv wi-day-rain-mix.svg flowers/
mv wi-day-thunderstorm.svg flowers/
mv wi-time-1.svg flowers/
mv wi-time-2.svg flowers/
mv wi-time-3.svg flowers/
mv wi-time-4.svg flowers/
mv wi-time-5.svg flowers/
mv wi-time-6.svg flowers/
mv wi-time-7.svg flowers/
mv wi-time-8.svg flowers/
mv wi-time-9.svg flowers/
mv wi-time-10.svg flowers/
mv wi-time-11.svg flowers/
mv wi-time-12.svg flowers/
mv wi-day-windy.svg flowers/
mv wi-raindrops.svg flowers/
mv wi-day-sunny-overcast.svg flowers/
mv wi-night-alt-partly-cloudy.svg flowers/
mv wi-showers.svg flowers/
mv wi-day-light-wind.svg flowers/
mv wi-day-fog.svg flowers/
mv wi-strong-wind.svg flowers/
mv wi-flood.svg flowers/
mv wi-day-cloudy-high.svg flowers/
mv wi-day-cloudy-windy.svg flowers/
mv wi-alien.svg flowers/
mv wi-earthquake.svg flowers/
mv wi-sandstorm.svg flowers/
mv wi-smog.svg flowers/
mv wi-fire.svg flowers/
mv wi-lightning.svg flowers/
mv wi-day-sunny.svg flowers/
mv wi-humidity.svg flowers/
mv wi-umbrella.svg flowers/
mv wi-windy.svg flowers/
mv wi-tornado.svg flowers/
mv wi-dust.svg flowers/
mv wi-fog.svg flowers/
mv wi-cloud.svg flowers/
mv wi-cloudy.svg flowers/
mv wi-night-cloudy.svg flowers/
mv wi-day-cloudy.svg flowers/
mv wi-night-clear.svg flowers/
mv wi-stars.svg flowers/
mv wi-night-partly-cloudy.svg flowers/
mv wi-hurricane.svg flowers/
mv wi-wind-deg.svg flowers/
mv wi-thunderstorm.svg flowers/
mv wi-snow.svg flowers/
mv wi-rain-mix.svg flowers/
mv wi-snow-wind.svg flowers/
mv wi-sprinkle.svg flowers/
mv wi-day-snow.svg flowers/
mv wi-day-hail.svg flowers/
mv wi-day-lightning.svg flowers/
mv wi-day-rain.svg flowers/
mv wi-day-showers.svg flowers/
mv wi-cloud-down.svg flowers/
mv wi-cloud-refresh.svg flowers/
mv wi-cloud-up.svg flowers/
mv wi-rain-wind.svg flowers/
mv wi-day-snow-wind.svg flowers/
mv wi-rain.svg flowers/
mv wi-sleet.svg flowers/
mv wi-day-sleet.svg flowers/
mv wi-day-sleet-storm.svg flowers/
mv wi-day-haze.svg flowers/
mv wi-smoke.svg flowers/
mv wi-snowflake-cold.svg flowers/
mv wi-hail.svg flowers/
mv wi-night-alt-sleet-storm.svg flowers/
mv wi-hot.svg flowers/
mv wi-night-thunderstorm.svg flowers/
mv wi-storm-showers.svg flowers/
mv wi-night-snow.svg flowers/
mv wi-small-craft-advisory.svg flowers/
mv wi-storm-warning.svg flowers/
mv wi-hurricane-warning.svg flowers/
mv wi-gale-warning.svg flowers/
mv wi-barometer.svg flowers/
mv wi-horizon.svg flowers/
mv wi-horizon-alt.svg flowers/
mv wi-meteor.svg flowers/
mv wi-moonrise.svg flowers/
mv wi-moonset.svg flowers/
mv wi-sunset.svg flowers/
mv wi-sunrise.svg flowers/
mv wi-day-cloudy-gusts.svg flowers/
mv wi-day-cloudy-windy.svg flowers/

