capture: false
LMS:
  active: true
  IP: "192.168.1.25"
  port: 9000
  player: "b8:27:eb:70:71:5c"
  remaining: true
RGB:
  scroll_limit: 28
  mapper: "U-maper;Rotate:180"
  fontfile: "font/LCDM2U__.TTF"
  fontfile2: "font/Roboto-Black.ttf"
  folding: true
  experiment: false
  rows: 64
  cols: 64
  hardware: adafruit-hat-pwm
  layout: full
  daybright: 30
  nightbright: 30
  showbright: false
  colorgrad1: "45a24740"
  colorgrad2: "0f344340"
transport:
  offset: 25
  route: "Red,47"
  #stop: "place-cntsq,1816,2755,1123"
  stop: "place-cntsq,1816"
  apiEnv: MBTA_API_KEY_V3
  active:
    days: 
      - 1
      - 2
      - 3
      - 4
      - 5
    from: "04:50 AM"
    until: "06:30 AM"
    window: 30
simple:
  style: 'style="fill: %s" fill-opacity="1.0" stroke-opacity="0.4" stroke="black" stroke-width="1"'
  parallel: 1
  chain: 2
  width: 128
  height: 64
  detail: true
  clock:
    width: 64
    height: 64
  icon:
    main:
      alpha: 0.60
      width: 27
      scale: 0.90
    wind:
      alpha: 0.95
      width: 24
      scale: 0.65
full:
  style: 'style="fill: %s" fill-opacity="1.0" stroke-opacity="0.4" stroke="midnightblue" stroke-width="2"'
  detail: false
  parallel: 1
  chain: 4
  width: 128
  height: 128
  clock:
    width: 128
    height: 128
  icon:
    main:
      alpha: 0.60
      width: 54
      scale: 1.80
    wind:
      alpha: 0.95
      width: 48
      scale: 1.3
jumbo:
  style: 'style="fill: %s" fill-opacity="1.0" stroke-opacity="0.4" stroke="midnightblue" stroke-width="3"'
  detail: false
  parallel: 1
  chain: 9
  width: 192
  height: 192
  clock:
    width: 192
    height: 192
  icon:
    main:
      alpha: 0.60
      width: 81
      scale: 2.70
    wind:
      alpha: 0.95
      width: 72
      scale: 1.95
feeds:
  -
    title: "BBC News UK"
    link: "http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/front_page/rss.xml"
    active: yes
#  -
#    title: "CNN: U.S."
#    link: "http://rss.cnn.com/rss/cnn_us.rss"
#    active: yes
  -
    title: "BBC News International"
    link: "http://feeds.bbci.co.uk/news/world/rss.xml"
    active: yes
#  -
#    title: "CNN: Top Stories"
#    link: "http://rss.cnn.com/rss/cnn_topstories.rss"
#    active: no
news:
  detail: true
  active: true
  window: 
    time: 00:15
    duration: 3
    repeat: 30